name: 自动压缩并发布 Release

on:
  push:
    branches:
      - master     # 只允许 master 分支
    tags:
      - 'v*'        # 只在打 tag 时

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 打包文件夹1和文件2
        run: 
          zip -r GDUFE-master-thesis.zip figures fonts includefile gdufe_master_thesis.cls gdufe_master_thesis_template.tex reference.bib

      - name: 创建 Release 并上传压缩包
        uses: softprops/action-gh-release@v2
        with:
          files: GDUFE-master-thesis.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
